baseURL: "https://84piranhas.github.io/"
title: 84piranhas
publishDir: "docs"
paginate: 5.0
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

menu:
    main:
        - name: Search
          url: search/
          weight: 1
        # - name: Archive
        #   url: archives
        #   weight: 5
        - name: Tags
          url: tags/
          weight: 10
        # - name: Series
        #   url: series/
        #   weight: 15
        # - name: Categories
        #   url: categories/
        #   weight: 20
        # - name: Code ser
        #   url: series/code
        #   weight: 21
        - name: CryptoCurrency
          url: categories/crypto
          weight: 22
        # - name: Code tag
        #   url: tags/code
        #   weight: 23

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
    disableXML: true
    # minifyOutput: true

# languages:
#    en:
#        languageName: "English"
#        # languagedirection: rtl
#        # weight: 3
#        # title: PaperMod RTL
#        # homeInfoParams:
#        #     Title: "Hi there \U0001F44B"
#        #     Content: Welcome to RTL layout
#        weight: 1
#        title: English
#        #profileMode:
#         #   enabled: true
#         #   title: PaperMod
#         #   # imageUrl: "#"
#         #   # imageTitle: my image
#         #   # imageWidth: 120
#         #   # imageHeight: 120
#         #   subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#         #   buttons:
#         #       - name: Blog
#         #         url: posts
#         #       - name: Tags
#         #         url: tags
#        menu:
#            main:
#                - name: Archive
#                  url: archives
#                  weight: 5
#                - name: Search
#                  url: search/
#                  weight: 10
#                - name: Tags
#                  url: tags/
#                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: false
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'
    disableSpecial1stPost: true

    custom_css: ["css/try.css"]

    label:
      icon: /android-chrome-512x512_grey.png

    profileMode:
        enabled: false
        title: ""
        imageUrl: "/android-chrome-512x512_old2.png"
        imageTitle: piranha_blue_eye
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    # homeInfoParams:
    #   Title: ""    
    #   Content: >
    #        ![alt text](/apple-touch-icon.png "piranha")
    #        <p style="text-align:center">hjkh<img class="center" src ="/apple-touch-icon.png"> jno<p>



    # socialIcons:
    #   #  - name: twitter
    #   #    url: "#"
    #   #  - name: stackoverflow
    #   #    url: "#"
    #   #  - name: codepen
    #   #    url: "#"
    #   #  - name: linkedin
    #   #    url: "#"
    #   #  - name: github
    #   #    url: "https://github.com/84piranhas/84piranhas.github.io"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
